name: Renovate automerge
on: pull_request

jobs:
    auto-merge:
      runs-on: ubuntu-latest
      steps:
        - name: Wait for other checks to succeed
          uses: lewagon/wait-on-check-action@v1.3.1
          with:
            ref: ${{ github.event.pull_request.head.sha }}
            running-workflow-name: 'auto-merge'
            repo-token: ${{ secrets.GITHUB_TOKEN }}
            wait-interval: 180
            allowed-conclusions: success
        - name: Enable auto-merge for Dependabot PRs
          if: contains(github.event.pull_request.body, format('**Automerge**{0} Enabled.', ':'))
          run : |
            gh pr review --approve "$PR_URL"
            gh pr merge --auto --merge "$PR_URL"
          env:
            PR_URL: ${{github.event.pull_request.html_url}}
            GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
